---
- name: Universal AWS Infrastructure Setup
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
    - name: aws_access_key
      prompt: "Enter AWS Access Key ID"
      private: no
    - name: aws_secret_key
      prompt: "Enter AWS Secret Access Key"
      private: yes
    - name: aws_region
      prompt: "us-east-1"
      private: no
      default: "us-east-1"

  tasks:
    # 1. Create the VPC
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "CeylonaAcademy-VPC"
        cidr_block: "172.33.0.0/16"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: present
        tags:
          Name: "CeylonaAcademy-VPC"
      register: vpc_result

    # 2. Create Internet Gateway
    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: present
      register: igw_result

    # 3. Create Subnet
    - name: Create Public Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        cidr: "172.33.1.0/24"
        map_public: yes
        tags:
          Name: "CeylonaAcademy-Public-Subnet"
      register: subnet_result

    # 4. Create Network ACL with Specific Rules
    - name: Create Custom Network ACL with Specific Rules
      community.aws.ec2_vpc_nacl:
        vpc_id: "{{ vpc_result.vpc.id }}"
        name: "CeylonaAcademy-NACL"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        subnets:
          - "{{ subnet_result.subnet.id }}"

        # --- INBOUND RULES (Matching your Screenshot) ---
        ingress:
          - [100, "tcp", "allow", "0.0.0.0/0", null, null, 80, 80]
          - [110, "tcp", "allow", "0.0.0.0/0", null, null, 443, 443]
          - [120, "tcp", "allow", "0.0.0.0/0", null, null, 22, 22]
          - [130, "tcp", "allow", "0.0.0.0/0", null, null, 1024, 65535]

        # --- OUTBOUND RULES (Matching your Screenshot) ---
        egress:
          - [100, "tcp", "allow", "0.0.0.0/0", null, null, 80, 80]
          - [110, "tcp", "allow", "0.0.0.0/0", null, null, 443, 443]
          - [120, "tcp", "allow", "0.0.0.0/0", null, null, 22, 22]
          - [130, "tcp", "allow", "0.0.0.0/0", null, null, 1024, 65535]

      register: nacl_result
      ignore_errors: true

    # 5. Route Table (Connects Subnet to Internet)
    - name: Set up Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        tags:
          Name: "CeylonaAcademy-Route-Table"
        subnets:
          - "{{ subnet_result.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id }}"

    # 6. Security Group (Firewall)
    # - name: Create Security Group
    #   amazon.aws.ec2_security_group:
    #     name: "CeylonaAcademy-Web-SG"
    #     description: "Allow SSH and HTTP"
    #     vpc_id: "{{ vpc_result.vpc.id }}"
    #     region: "{{ aws_region }}"
    #     aws_access_key: "{{ aws_access_key }}"
    #     aws_secret_key: "{{ aws_secret_key }}"
    #     rules:
    #       - proto: tcp
    #         ports: [80, 443, 22]
    #         cidr_ip: 0.0.0.0/0
    #   register: sg_result

    # 6. Security Group (UPDATED for Kubernetes)
    - name: Create Kubernetes Security Group
      amazon.aws.ec2_security_group:
        name: "Ceylona-K8s-SG"
        description: "Allow SSH, HTTP, and Internal K8s Traffic"
        vpc_id: "{{ vpc_result.vpc.id }}"
        rules:
          # External Access
          - proto: tcp
            ports: [22, 80, 443, 6443] # 6443 is for K8s API access
            cidr_ip: 0.0.0.0/0
          # Internal Cluster Communication (Crucial!)
          - proto: all
            group_name: "Ceylona-K8s-SG" # Allow all traffic from nodes in this same SG
      register: sg_result

    # --------------------------------------------------
    # 7. Find Ubuntu 24.04 AMI
    # --------------------------------------------------
    - name: Find latest Ubuntu 24.04 AMI
      amazon.aws.ec2_ami_info:
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        owners: ["099720109477"]
        filters:
          name: "ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"
          architecture: x86_64
      register: ubuntu_ami

    # --------------------------------------------------
    # 8. Launch EC2 (Idempotent)
    # --------------------------------------------------
    # - name: Launch EC2 Instance
    #   amazon.aws.ec2_instance:
    #     name: "CeylonaAcademy-Web-Server"
    #     region: "{{ aws_region }}"
    #     aws_access_key: "{{ aws_access_key }}"
    #     aws_secret_key: "{{ aws_secret_key }}"
    #     key_name: "virginia"
    #     instance_type: t3.micro

    #     image_id: "{{ (ubuntu_ami.images | sort(attribute='creation_date'))[-1].image_id }}"

    #     security_group: "{{ sg_result.group_id }}"
    #     vpc_subnet_id: "{{ subnet_result.subnet.id }}"

    #     network_interfaces:
    #       - assign_public_ip: true

    #     exact_count: 1
    #     filters:
    #       "tag:Name": "CeylonaAcademy-Web-Server"
    #       instance-state-name: running

    #     tags:
    #       Name: "CeylonaAcademy-Web-Server"
    #   register: ec2_result

    # 8. Launch EC2 Instances (UPDATED loop)
    - name: Launch Kubernetes Nodes
      amazon.aws.ec2_instance:
        name: "Ceylona-K8s-{{ item.name }}"
        region: "{{ aws_region }}"
        key_name: "virginia"
        instance_type: "{{ item.type }}" # t3.medium recommended for master
        image_id: "{{ (ubuntu_ami.images | sort(attribute='creation_date'))[-1].image_id }}"
        security_group: "{{ sg_result.group_id }}"
        vpc_subnet_id: "{{ subnet_result.subnet.id }}"
        network_interfaces: [{ assign_public_ip: true }]
        tags:
          Name: "Ceylona-K8s-{{ item.name }}"
          Role: "{{ item.role }}"
      loop:
        - { name: "Master", role: "control-plane", type: "t3.medium" }
        - { name: "Worker-1", role: "worker", type: "t3.small" }
        - { name: "Worker-2", role: "worker", type: "t3.small" }
      register: ec2_nodes

    # --------------------------------------------------
    # 9. Output the Public IP
    # --------------------------------------------------
    - name: Done!
      debug:
        msg: "Server created at IP: {{ ec2_result.instances[0].public_ip_address }}"

    - name: Debug - Show me EVERYTHING inside the variable
      debug:
        var: ec2_result
